spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mariadb://localhost:3306/toDoList
    username: root
    password: qwerty0922
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create

jwt:
  token-validity-in-seconds: 7776000000 #90일
  secretKey: json-web-token-secret-key-sign-with-member-api
